apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: pinger
  labels:
    app: ping
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
        - name: ping
          image: registry.hub.docker.com/ekowcharles/ping:20190215_001910_11b6b7f
          ports:
            - containerPort: 8993
              name: ping-port
      imagePullSecrets:
        - name: regcred
